namespace SmartTable.Client.Services;
 
public class LocalizationService
{
    private string _currentLanguage = "en"; 
 
    public string CurrentLanguage
    {
        get => _currentLanguage;
        set
        {
            if (_currentLanguage != value)
            {
                _currentLanguage = value;
                OnLanguageChanged?.Invoke();
            }
        }
    }
 
    public event Action? OnLanguageChanged;
 
    private readonly Dictionary<string, Dictionary<string, string>> _translations = new()
    {
        { "uk", new Dictionary<string, string> {
            { "Students", "Студенти" },
            { "Courses", "Курси" },
            { "Registrations", "Реєстрації" },
            { "AuditLogs", "Аудит Логи" },
            { "Total", "Всього" },
            { "Language", "Мова" },
            { "Search", "Пошук" },
            { "AddStudent", "Додати студента" },
            { "SearchByName", "Пошук за іменем, ПКК або громадянством..." },
            { "SearchByNameOrCourse", "Пошук за іменем або курсом..." },
            { "Name", "Ім'я" },
            { "Citizenship", "Громадянство" },
            { "PkkNumber", "Номер ПКК" },
            { "Actions", "Дії" },
            { "Edit", "Редагування" },
            { "StudentAdded", "Студента додано" },
            { "DataUpdated", "Дані оновлено" },
            { "Confirmation", "Підтвердження" },
            { "Delete", "Видалити" },
            { "DeleteQuestion", "Видалити реєстрацію студента" },
            { "Yes", "Так" },
            { "Cancel", "Скасувати" },
            { "Deleted", "Видалено" },
            { "AddCourse", "Додати курс" },
            { "CourseType", "Тип курсу" },
            { "Student", "Студент" },
            { "Course", "Курс" },
            { "Price", "Ціна" },
            { "Status", "Статус" },
            { "ArrivalDate", "Дата приїзду" },
            { "CoursePrice", "Ціна курсу" },
            { "InvoiceOrHotel", "Фактура / Готель" },
            { "NewRegistration", "Нова реєстрація" },
            { "NoRegistrationsFound", "Реєстрацій не знайдено" },
            { "ErrorLoadingRegistrations", "Помилка завантаження реєстрацій" },
            { "EditRegistration", "Редагування реєстрації" },
            { "RegistrationCreated", "Реєстрацію створено" },
            { "RegistrationUpdated", "Реєстрацію оновлено" },
            { "SaveError", "Помилка збереження" },
            { "DeleteError", "Помилка видалення" },
            { "PaymentMethod", "Спосіб оплати" },
            { "MedicalExam", "Медогляд (Badania lekarskie)" },
            { "PsychologicalExam", "Психоогляд (Badania psychol.)" },
            { "Translation", "Переклад (Tłumaczenie)" },
            { "PowerOfAttorney", "Довіреність (Pełnomocnictwo)" },
            { "HotelStayRange", "Готель: від — до (дати)" },
            { "CompanyName", "Firma (назва компанії)" },
            { "Notes", "Примітки (Notes)" },
            { "LeaveEmptyIfOwn", "Свої — залишити порожнім" },
            // ── Courses page ──────────────────────────────────
            { "SearchByTypeOrLanguage", "Пошук за типом або мовою..." },
            { "Language_col", "Мова" },
            { "NoCoursesFound", "Курсів не знайдено" },
            { "ErrorLoadingCourses", "Помилка завантаження курсів" },
            { "NewCourse", "Новий курс" },
            { "EditCourse", "Редагування курсу" },
            { "DeleteCourseQuestion", "Видалити курс" },
            { "CourseAdded", "Курс додано" },
            { "CourseUpdated", "Курс оновлено" },
            { "CourseDeleted", "Курс видалено" },
            { "SelectCourseType", "Оберіть тип курсу" },
            { "SelectLanguage", "Оберіть мову" },
            { "Add", "Додати" },
            { "Save", "Зберегти" },
        }},
        { "pl", new Dictionary<string, string> {
            { "Students", "Studenci" },
            { "Courses", "Kursy" },
            { "Registrations", "Rejestracje" },
            { "AuditLogs", "Logi Audytu" },
            { "Total", "Razem" },
            { "Language", "Język" },
            { "Search", "Szukaj" },
            { "AddStudent", "Dodaj studenta" },
            { "SearchByName", "Wyszukaj po imieniu, numerze PKK lub obywatelstwie..." },
            { "SearchByNameOrCourse", "Wyszukaj według imienia lub kursu..." },
            { "Name", "Imię" },
            { "Citizenship", "Obywatelstwo" },
            { "PkkNumber", "Numer PKK" },
            { "Actions", "Akcje" },
            { "Edit", "Edytuj" },
            { "StudentAdded", "Student został dodany" },
            { "DataUpdated", "Dane zostały zaktualizowane" },
            { "Confirmation", "Potwierdzenie" },
            { "Delete", "Usuń" },
            { "DeleteQuestion", "Czy na pewno chcesz usunąć rejestrację studenta" },
            { "Yes", "Tak" },
            { "Cancel", "Anuluj" },
            { "Deleted", "Usunięto" },
            { "AddCourse", "Dodaj kurs" },
            { "CourseType", "Rodzaj kursu" },
            { "Student", "Student" },
            { "Course", "Kurs" },
            { "Price", "Cena" },
            { "Status", "Status" },
            { "ArrivalDate", "Data przyjazdu" },
            { "CoursePrice", "Cena kursu" },
            { "InvoiceOrHotel", "Faktura / Hotel" },
            { "NewRegistration", "Nowa rejestracja" },
            { "NoRegistrationsFound", "Nie znaleziono rejestracji" },
            { "ErrorLoadingRegistrations", "Błąd ładowania rejestracji" },
            { "EditRegistration", "Edycja rejestracji" },
            { "RegistrationCreated", "Rejestracja została utworzona" },
            { "RegistrationUpdated", "Rejestracja została zaktualizowana" },
            { "SaveError", "Błąd zapisywania" },
            { "DeleteError", "Błąd usuwania" },
            { "PaymentMethod", "Sposób płatności" },
            { "MedicalExam", "Badania lekarskie" },
            { "PsychologicalExam", "Badania psychologiczne" },
            { "Translation", "Tłumaczenie" },
            { "PowerOfAttorney", "Pełnomocnictwo" },
            { "StayRange", "Hotel: od – do (daty)" },
            { "CompanyName", "Nazwa firmy" },
            { "Notes", "Notatki" },
            { "LeaveEmptyIfOwn", "Własne — pozostaw puste" },
            // ── Courses page ──────────────────────────────────
            { "SearchByTypeOrLanguage", "Szukaj po typie lub języku..." },
            { "Language_col", "Język" },
            { "NoCoursesFound", "Nie znaleziono kursów" },
            { "ErrorLoadingCourses", "Błąd ładowania kursów" },
            { "NewCourse", "Nowy kurs" },
            { "EditCourse", "Edycja kursu" },
            { "DeleteCourseQuestion", "Usuń kurs" },
            { "CourseAdded", "Kurs dodany" },
            { "CourseUpdated", "Kurs zaktualizowany" },
            { "CourseDeleted", "Kurs usunięty" },
            { "SelectCourseType", "Wybierz typ kursu" },
            { "SelectLanguage", "Wybierz język" },
            { "Add", "Dodaj" },
            { "Save", "Zapisz" },
        }},
        { "en", new Dictionary<string, string> {
            { "Students", "Students" },
            { "Courses", "Courses" },
            { "Registrations", "Registrations" },
            { "AuditLogs", "Audit Logs" },
            { "Total", "Total" },
            { "Language", "Language" },
            { "Search", "Search" },
            { "AddStudent", "Add Student" },
            { "SearchByName", "Search by name, PKK number or citizenship..." },
            { "SearchByNameOrCourse", "Search by name or course..." },
            { "Name", "Name" },
            { "Citizenship", "Citizenship" },
            { "PkkNumber", "PKK Number" },
            { "Actions", "Actions" },
            { "Edit", "Edit" },
            { "StudentAdded", "Student added" },
            { "DataUpdated", "Data updated" },
            { "Confirmation", "Confirmation" },
            { "Delete", "Delete" },
            { "DeleteQuestion", "Are you sure you want to delete the enrollment for" },
            { "Yes", "Yes" },
            { "Cancel", "Cancel" },
            { "Deleted", "Deleted" },
            { "AddCourse", "Add Course" },
            { "CourseType", "Course Type" },
            { "Student", "Student" },
            { "Course", "Course" },
            { "Price", "Price" },
            { "Status", "Status" },
            { "ArrivalDate", "Arrival Date" },
            { "CoursePrice", "Course Price" },
            { "InvoiceOrHotel", "Invoice / Hotel" },
            { "NewRegistration", "New Registration" },
            { "NoRegistrationsFound", "No registrations found" },
            { "ErrorLoadingRegistrations", "Error loading registrations" },
            { "EditRegistration", "Edit Registration" },
            { "RegistrationCreated", "Registration created" },
            { "RegistrationUpdated", "Registration updated" },
            { "SaveError", "Save error" },
            { "DeleteError", "Delete error" },
            { "PaymentMethod", "Payment Method" },
            { "MedicalExam", "Medical Exam" },
            { "PsychologicalExam", "Psychological Exam" },
            { "Translation", "Translation" },
            { "PowerOfAttorney", "Power of Attorney" },
            { "StayRange", "Hotel stay: from – to (dates)" },
            { "CompanyName", "Company Name" },
            { "Notes", "Notes" },
            { "LeaveEmptyIfOwn", "Own — leave blank" },
            // ── Courses page ──────────────────────────────────
            { "SearchByTypeOrLanguage", "Search by type or language..." },
            { "Language_col", "Language" },
            { "NoCoursesFound", "No courses found" },
            { "ErrorLoadingCourses", "Error loading courses" },
            { "NewCourse", "New course" },
            { "EditCourse", "Edit course" },
            { "DeleteCourseQuestion", "Delete course" },
            { "CourseAdded", "Course added" },
            { "CourseUpdated", "Course updated" },
            { "CourseDeleted", "Course deleted" },
            { "SelectCourseType", "Select course type" },
            { "SelectLanguage", "Select language" },
            { "Add", "Add" },
            { "Save", "Save" },
        }}
    };
 
    public string GetString(string key)
    {
        if (_translations.TryGetValue(_currentLanguage, out var langDict) &&
            langDict.TryGetValue(key, out var value))
            return value;
        return key;
    }
}