namespace SmartTable.Client.Services;
 
public class LocalizationService
{
    private string _currentLanguage = "en"; 
 
    public string CurrentLanguage
    {
        get => _currentLanguage;
        set
        {
            if (_currentLanguage != value)
            {
                _currentLanguage = value;
                OnLanguageChanged?.Invoke();
            }
        }
    }
 
    public event Action? OnLanguageChanged;
 
    private readonly Dictionary<string, Dictionary<string, string>> _translations = new()
    {
        { "uk", new Dictionary<string, string> {
            { "Students", "Студенти" },
            { "Courses", "Курси" },
            { "Registrations", "Реєстрації" },
            { "AuditLogs", "Аудит Логи" },
            { "Total", "Всього" },
            { "Language", "Мова" },
            { "Search", "Пошук" },
            { "AddStudent", "Додати студента" },
            { "SearchByName", "Пошук за іменем, ПКК або громадянством..." },
            { "SearchByNameOrCourse", "Пошук за іменем або курсом..." },
            { "Name", "Ім'я" },
            { "Citizenship", "Громадянство" },
            { "PkkNumber", "Номер ПКК" },
            { "Actions", "Дії" },
            { "Edit", "Редагування" },
            { "StudentAdded", "Студента додано" },
            { "DataUpdated", "Дані оновлено" },
            { "Confirmation", "Підтвердження" },
            { "Delete", "Видалити" },
            { "DeleteQuestion", "Видалити реєстрацію студента" },
            { "Yes", "Так" },
            { "Cancel", "Скасувати" },
            { "Deleted", "Видалено" },
            { "AddCourse", "Додати курс" },
            { "CourseType", "Тип курсу" },
            { "Student", "Студент" },
            { "Course", "Курс" },
            { "Price", "Ціна" },
            { "Status", "Статус" },
            { "ArrivalDate", "Дата приїзду" },
            { "CoursePrice", "Ціна курсу" },
            { "InvoiceOrHotel", "Фактура / Готель" },
            { "NewRegistration", "Нова реєстрація" },
            { "NoRegistrationsFound", "Реєстрацій не знайдено" },
            { "ErrorLoadingRegistrations", "Помилка завантаження реєстрацій" },
            { "EditRegistration", "Редагування реєстрації" },
            { "RegistrationCreated", "Реєстрацію створено" },
            { "RegistrationUpdated", "Реєстрацію оновлено" },
            { "SaveError", "Помилка збереження" },
            { "DeleteError", "Помилка видалення" },
            { "PaymentMethod", "Спосіб оплати" },
            { "MedicalExam", "Медогляд (Badania lekarskie)" },
            { "PsychologicalExam", "Психоогляд (Badania psychol.)" },
            { "Translation", "Переклад (Tłumaczenie)" },
            { "PowerOfAttorney", "Довіреність (Pełnomocnictwo)" },
            { "HotelStayRange", "Готель: від — до (дати)" },
            { "CompanyName", "Firma (назва компанії)" },
            { "Notes", "Примітки (Notes)" },
            { "LeaveEmptyIfOwn", "Свої — залишити порожнім" },
            { "SearchByTypeOrLanguage", "Пошук за типом або мовою..." },
            { "Language_col", "Мова" },
            { "NoCoursesFound", "Курсів не знайдено" },
            { "ErrorLoadingCourses", "Помилка завантаження курсів" },
            { "NewCourse", "Новий курс" },
            { "EditCourse", "Редагування курсу" },
            { "DeleteCourseQuestion", "Видалити курс" },
            { "CourseAdded", "Курс додано" },
            { "CourseUpdated", "Курс оновлено" },
            { "CourseDeleted", "Курс видалено" },
            { "SelectCourseType", "Оберіть тип курсу" },
            { "SelectLanguage", "Оберіть мову" },
            { "Add", "Додати" },
            { "Save", "Зберегти" },

            // ── Kandydaci (Candidates) 🧑‍─────────────────────────
            { "CandidatesPageTitle", "Кандидати (Очікуючі)" },
            { "CandidatesTotalInQueue", "Всього в черзі" },
            { "SearchByNameOrPhone", "Пошук за іменем, прізвищем або телефоном..." },
            { "CandidateCol", "Кандидат" },
            { "PhoneCol", "Телефон" },
            { "StatusCancelled", "Анульовано" },
            { "StatusRegistered", "Зареєстровано" },
            { "StatusFinished", "Завершено" },
            { "StatusDropped", "Викреслено" },
            { "StatusWaiting", "Очікує" },
            { "ActionCol", "Дія" },
            { "TooltipAddCourse", "Додати ще курс" },
            { "TooltipRegister", "Зареєструвати (Призначити на курс)" },
            { "TooltipFinishCourse", "Завершити курс" },
            { "TooltipDropStudent", "Викреслити зі списку студентів" },
            { "TooltipRemoveCourse", "Прибрати з курсу (Помилка)" },
            { "TooltipCancelRegistration", "Анулювати реєстрацію" },
            { "TooltipDeletePermanently", "Видалити реєстрацію назавжди" },
            { "CandidateDetails", "Деталі кандидата" },
            { "FullNameLabel", "Ім'я та прізвище" },
            { "PhoneNumberLabel", "Номер телефону" },
            { "ContactMethodLabel", "Спосіб контакту" },
            { "PreferredCourseLabel", "Бажаний курс" },
            { "PreferredDateLabel", "Бажана дата" },
            { "AssignToCoursesTitle", "Призначити на курси" },
            { "CandidateAssignedSuccess", "Кандидата зареєстровано на обрані курси!" },
            { "AssignError", "Помилка під час призначення" },
            { "SystemError", "Сталася системна помилка. Спробуйте ще раз." },
            { "FinishCourseTitle", "Завершити курс" },
            { "DropFromListTitle", "Викреслити зі списку" },
            { "RemoveCourseTitle", "Прибрати з курсу (Помилка)" },
            { "CancelRegistrationTitle", "Анулювати реєстрацію" },
            { "StatusUpdated", "Статус оновлено." },
            { "UpdateError", "Помилка під час оновлення" },
            { "EnrollmentRemoved", "Призначення на курс видалено." },
            { "RemoveFromCourseError", "Помилка під час видалення з курсу." },
            { "CourseStatusUpdated", "Статус курсу оновлено." },
            { "DeleteCandidateConfirmMessage", "Ви справді хочете назавжди видалити кандидата" },
            { "YesDelete", "Так, видалити" },
            { "CandidateDeleted", "Кандидата видалено назавжди." },
            { "DeleteErrorGeneric", "Помилка під час видалення." },
            { "ErrorLoadingData", "Помилка завантаження даних" },

            // ── Registrations (форма реєстрації) 📝 ─────────────────
            { "RegistrationsPageTitle", "Реєстрації кандидатів" },
            { "AddRegistration", "Додати реєстрацію" },
            { "ContactCol", "Контакт" },
            { "PreferredTermCol", "Бажаний термін" },
            { "CompanyCol", "Фірма" },
            { "PrivatelyText", "приватно" },
            { "HotelCol", "Готель" },
            { "HotelYes", "Так" },
            { "HotelNo", "Ні" },
            { "HotelUnknown", "Невідомо" },
            { "SavedSuccessfully", "Успішно збережено" },
            { "SaveErrorDuplicate", "Помилка збереження (можливий дублікат)" },

            // ── Audit Logs 🔍 ────────────────────────────────────────
            { "Refresh", "Оновити" },
            { "UserCol", "Користувач" },
            { "EntityCol", "Сутність" },
            { "ActionColLog", "Дія" },
            { "GoToCol", "Перейти" },

            // ── Admini (Admin Users) ──────────────────────────────
            { "AdminManagementTitle", "Керування обліковими записами адмінів" },
            { "TotalAdmins", "Всього" },
            { "AddAdmin", "Додати адміна" },
            { "LoginCol", "Логін" },
            { "RoleCol", "Роль" },
            { "CreatedAtCol", "Створено" },
            { "DeleteAccountTooltip", "Видалити акаунт" },
            { "NoAccountsFound", "Немає акаунтів" },
            { "LoadAdminsError", "Помилка завантаження списку адмінів" },
            { "AdminCreatedSuccess", "Акаунт адміна створено." },
            { "CreateAdminError", "Помилка створення акаунту." },
            { "DeleteAdminConfirmMessage", "Видалити акаунт адміна" },
            { "AdminDeletedSuccess", "Акаунт видалено." },
            { "DeleteAdminError", "Помилка видалення акаунту." },
            { "PasswordLabel", "Пароль" },
            { "PasswordHelperText", "Мінімум 8 символів" },
            { "CreateButton", "Створити" },

            // ── Dialogs: Assign / Cancel / ChangeStatus 📋 ───────────
            { "ChooseCoursesFor", "Оберіть курси для кандидата" },
            { "SelectAllText", "Вибрати всі" },
            { "MarkCoursesLabel", "Позначте курси (можна декілька)" },
            { "RequiredCourseError", "Потрібно обрати хоча б один курс" },
            { "AssignToCourses", "Призначити на курси" },
            { "CancelReasonPrompt", "Вкажіть причину анулювання реєстрації для кандидата" },
            { "CancelReasonLabel", "Причина анулювання" },
            { "CancelReasonRequired", "Потрібно вказати причину анулювання!" },
            { "CancelReasonPlaceholder", "На жаль, кандидат відмовився..." },
            { "GoBack", "Назад" },
            { "ConfirmCancellation", "Підтвердити анулювання" },
            { "CandidateLabel", "Кандидат" },
            { "ActionLabel", "Дія" },
            { "SelectCourseLabel", "Оберіть курс" },
            { "SelectCourseRequired", "Потрібно обрати курс" },
            { "NoActiveCoursesWarning", "Немає активних курсів для вибору." },
            { "ReasonRequiredError", "Потрібно вказати причину!" },
            { "RemoveCourseWarning", "Ця дія назавжди видалить призначення кандидата на обраний курс. Використовуйте лише у випадку помилки!" },
            { "Confirm", "Підтвердити" },
            { "ActionCancelling", "Анулювання реєстрації" },
            { "ActionDropping", "Викреслення зі списку студентів" },
            { "ActionFinishing", "Завершення курсу" },
            { "ActionRemoving", "Видалення призначення (помилка)" },
            { "ActionGeneric", "Зміна статусу" },
            { "NotesOptional", "Примітки (необов'язково)" },
            { "ReasonRequiredLabel", "Причина (обов'язково)" },
            { "PlaceholderFinished", "Напр. Сертифікат видано..." },
            { "PlaceholderReason", "Вкажіть причину..." },

            // ── StudentDialog 👤 ──────────────────────────────────────
            { "DateOfBirth", "Дата народження" },
            { "RequiredField", "Обов'язкове поле" },
            { "OptionalPlaceholder", "Необов'язково" },

            // ── Login ──────────────────────────────────────────────
            { "LoginToContinue", "Увійдіть, щоб продовжити" },
            { "LoginLabel", "Логін" },
            { "LoginButton", "Увійти" },
            { "FillLoginPassword", "Введіть логін і пароль." },
            { "LoginError", "Помилка входу." },
            { "LoggedInAs", "Ви увійшли як" },
            { "LogoutButtonText", "Вийти" },

            // ── SmartPriceField ────────────────────────────────────
            { "ChoosePricePlaceholder", "Оберіть або введіть суму" },

            // ── Students page ──────────────────────────────────────
            { "StudentsPageTitle", "Студенти (Обслуговування після приїзду)" },
            { "StudentsTotalCaption", "Всього студентів" },
            { "NewStudentsAutoNote", "нові студенти з'являються автоматично після призначення кандидата на курс на сторінці Кандидати" },
            { "SearchStudents", "Пошук за іменем, прізвищем, ПКК, громадянством або курсом..." },
            { "FullNameCol", "Ім'я та прізвище" },
            { "CoursesCol", "Курси" },
            { "NoActiveCourses", "Немає активних курсів" },
            { "OverallStatusCol", "Загальний статус" },
            { "AttendanceCol", "Присутність" },
            { "PaymentsCol", "Оплати" },
            { "EditBasicDataTooltip", "Редагувати основні дані" },
            { "DeleteStudentTooltip", "Видалити студента" },
            { "NoCourseAssignedInfo", "Цей студент ще не має призначеного курсу. Призначення відбувається на сторінці Kandydaci." },
            { "AttendanceDocumentsTab", "Присутність і документи" },
            { "AttendanceHeader", "Присутність" },
            { "AttendanceStatusLabel", "Статус присутності" },
            { "ArrivalWaiting", "Очікує на приїзд" },
            { "ArrivalArrived", "Приїхав" },
            { "ArrivalNoShow", "Не приїхав" },
            { "ArrivalLate", "Спізнюється" },
            { "ArrivalDateLabel", "Дата приїзду" },
            { "DocumentsHeader", "Документи" },
            { "DocumentsStatusLabel", "Статус документів" },
            { "DocNotChecked", "Не перевірено" },
            { "DocMissing", "Відсутні" },
            { "DocPartial", "Частково" },
            { "DocReceived", "Отримано" },
            { "DocNotRequired", "Не потрібно" },
            { "PassportLabel", "Паспорт" },
            { "DrivingLicenseLabel", "Водійське посвідчення" },
            { "PkkPkzLabel", "PKK / PKZ" },
            { "MedicalExamShortLabel", "Медогляд" },
            { "PaymentsTab", "Оплати" },
            { "PaymentStatusLabel", "Статус оплати" },
            { "PayUnpaid", "Не оплачено" },
            { "PayPartial", "Частково оплачено" },
            { "PayPaid", "Оплачено" },
            { "PayOverpaid", "Переплата" },
            { "PayNotRequired", "Не потрібно" },
            { "SuggestedLabel", "Рекомендовано" },
            { "PayCash", "Готівка" },
            { "PayBankTransfer", "Переказ" },
            { "PayCompany", "Платить фірма" },
            { "PayMixed", "Змішано" },
            { "PayOther", "Інше" },
            { "InvoiceLabel", "Рахунок-фактура" },
            { "CoursePriceLabel", "Ціна курсу (PLN)" },
            { "AmountPaidLabel", "Сплачена сума (PLN)" },
            { "RemainingLabel", "Залишилось" },
            { "OverpaidLabel", "Переплата" },
            { "FullyPaidLabel", "Оплачено повністю" },
            { "TotalDueWithServicesLabel", "До сплати разом з послугами" },
            { "PaymentNotesLabel", "Примітки до оплати" },
            { "ServicesHotelTab", "Послуги та готель" },
            { "AdditionalServicesHeader", "Додаткові послуги" },
            { "MedicalExamCheckboxLabel", "Медичний огляд" },
            { "PsychExamCheckboxLabel", "Психологічний огляд" },
            { "TranslationCheckboxLabel", "Переклад" },
            { "PowerOfAttorneyCheckboxLabel", "Довіреність" },
            { "PkkPkzFeeLabel", "PKK / PKZ (оплата)" },
            { "HotelHeader", "Готель" },
            { "NeedsHotelLabel", "Потрібен готель" },
            { "HotelStatusLabel", "Статус готелю" },
            { "HotelNotRequired", "Не потрібно" },
            { "HotelNeeded", "Потрібен" },
            { "HotelReserved", "Заброньовано" },
            { "HotelCheckedIn", "Заселено" },
            { "HotelCancelled", "Скасовано" },
            { "HotelFromLabel", "Від" },
            { "HotelToLabel", "До" },
            { "HotelStayRangeLabel", "Період перебування (текст, необов'язково)" },
            { "FinalStatusTab", "Фінальний статус" },
            { "CourseStatusLabel", "Статус курсу" },
            { "CourseInProgress", "Триває" },
            { "OfficeNotesLabel", "Примітки офісу" },
            { "OfficeNotesPlaceholder", "Тільки нестандартні ситуації..." },
            { "SaveDataButton", "Зберегти дані" },
            { "NoStudentsInDb", "У базі немає студентів" },
            { "EnrollmentSaved", "Дані курсу студента збережено." },
            { "EnrollmentSaveError", "Помилка збереження даних." },
            { "EditDataTitle", "Редагувати дані" },
            { "DeleteStudentConfirmMessage", "Видалити студента" },

            // ── RegistrationDialog 📝 ──────────────────────────────────
            { "CandidateDataHeader", "Дані кандидата" },
            { "CountryCodeLabel", "Код країни" },
            { "PhoneNumberFieldLabel", "Номер телефону" },
            { "PhoneFormatHelper", "Формат: 500 111 222 (пробіли будуть прибрані автоматично)" },
            { "ContactLanguageLabel", "Мова спілкування" },
            { "RegistrationSourceLabel", "Джерело звернення" },
            { "SourcePhone", "Телефон" },
            { "SourceWhatsApp", "WhatsApp" },
            { "SourceCompany", "Фірма" },
            { "ContactHeader", "Контакт" },
            { "PrimaryContactLabel", "Основний спосіб контакту" },
            { "ContactPhoneCall", "Телефонний дзвінок" },
            { "ContactViber", "Viber" },
            { "ContactTelegram", "Telegram" },
            { "ContactMessenger", "Messenger" },
            { "ContactSms", "SMS" },
            { "ContactNotesLabel", "Примітки щодо контакту" },
            { "ContactNotesPlaceholder", "Напр. Не дзвонити після 18:00" },
            { "CourseAndDateHeader", "Курс і термін (побажання клієнта)" },
            { "CourseTypeLabel", "Тип курсу" },
            { "CourseInfoOnly", "Info (лише примітка)" },
            { "PreferredCourseDateLabel", "Бажаний термін курсу" },
            { "PlannedArrivalDateLabel", "Планована дата приїзду" },
            { "DateNotesLabel", "Примітки щодо терміну" },
            { "CompanyHeader", "Фірма" },
            { "PrivatePersonOption", "Приватна особа" },
            { "CompanyOption", "Фірма" },
            { "UnknownOption", "Невідомо" },
            { "CompanyNameFieldLabel", "Фірма (назва)" },
            { "HotelDialogHeader", "Готель" },
            { "HotelFromDialogLabel", "Готель від" },
            { "HotelToDialogLabel", "Готель до" },
            { "HotelNotesLabel", "Примітки щодо готелю" },
            { "StatusAndNotesHeader", "Статус і примітки" },
            { "RegistrationStatusLabel", "Статус реєстрації" },
            { "RegStatusNew", "Нове звернення" },
            { "RegStatusContacted", "Зв'язались" },
            { "RegStatusWaitingConfirmation", "Очікує підтвердження" },
            { "RegStatusConfirmed", "Підтверджено" },
            { "RegStatusAssigned", "Призначено на курс" },
            { "RegistrationNotesLabel", "Примітки до реєстрації" },
            { "UpdateButton", "Оновити" },
            { "CandidatesNav", "Кандидати" },
            { "AdminsNav", "Адміни" },
            { "CourseDatesHeader", "Терміни курсу" },
            { "AddDateButton", "Додати термін" },
            { "StartDateLabel", "Дата від" },
            { "EndDateLabelShort", "Дата до" },
            { "NoDatesYet", "Ще немає запланованих термінів" },
            { "EnrolledStudentsHeader", "Записано студентів" },
            { "NoStudentsForDate", "На цей термін ніхто не записаний" },
            { "DeleteDateTooltip", "Видалити термін" },
            { "SelectDateForCourse", "Оберіть термін (необов'язково)" },
            { "NoDateSelected", "Без конкретного терміну" },
            { "DeleteDateConfirmMessage", "Видалити термін" },
            { "FutureTermsCountCol", "Майбутніх термінів" },
            { "NearestTermCol", "Найближчий термін" },
            { "OpenAction", "Відкрити" },
            { "TemplatesHeader", "Шаблони генерації термінів" },
            { "AddTemplateButton", "Додати шаблон" },
            { "NoTemplatesYet", "Ще немає жодного шаблону" },
            { "GenerateButton", "Згенерувати" },
            { "SourceCol", "Джерело" },
            { "SourceGenerated", "Згенеровано" },
            { "SourceManual", "Вручну" },
            { "ManuallyModifiedTooltip", "Відредаговано вручну після генерації" },
            { "TermStatusLabel", "Статус терміну" },
            { "TermStatusPlanned", "Заплановано" },
            { "TermStatusActive", "Активний" },
            { "TermStatusFinished", "Завершено" },
            { "TermStatusCancelled", "Скасовано" },
            { "TermStatusMoved", "Перенесено" },
            { "TrainerLabel", "Тренер" },
            { "DefaultPriceLabel", "Ціна за замовчуванням" },
            { "SeatLimitLabel", "Ліміт місць" },
            { "TermNotesLabel", "Примітки до терміну" },
            { "TemplateModeLabel", "Режим створення термінів" },
            { "TemplateModeCyclic", "Циклічний" },
            { "TemplateModeManual", "Ручний" },
            { "DayOfWeekLabel", "День тижня" },
            { "DayMonday", "Понеділок" },
            { "DayTuesday", "Вівторок" },
            { "DayWednesday", "Середа" },
            { "DayThursday", "Четвер" },
            { "DayFriday", "П'ятниця" },
            { "DaySaturday", "Субота" },
            { "DaySunday", "Неділя" },
            { "FrequencyLabel", "Частота" },
            { "FrequencyWeekly", "Щотижня" },
            { "FrequencyBiweekly", "Раз на 2 тижні" },
            { "FrequencyEvery3Weeks", "Раз на 3 тижні" },
            { "FrequencyMonthly", "Раз на місяць" },
            { "GenerateFromLabel", "Генерувати від" },
            { "GenerateToLabel", "Генерувати до" },
            { "DefaultDurationLabel", "Тривалість курсу (днів)" },
            { "TemplateActiveLabel", "Активний" },
            { "GeneratedCountMessage", "Створено термінів" },
            { "SkippedCountMessage", "Пропущено (вже існують)" },
            { "GenerateError", "Помилка під час генерації" },
            { "DeleteTemplateConfirmMessage", "Видалити цей шаблон?" },
            { "NoAvailableTermsForCourse", "Немає доступних термінів для цього курсу" },
            { "OpenStudentCardAction", "Відкрити картку студента" },
            { "CourseVariantPreview", "Варіант курсу" },
            { "CourseTypeHelper", "Оберіть зі списку або впишіть нове значення" },
            { "LanguageHelper", "Оберіть зі списку або впишіть нове значення" },
            { "Month1", "Січень" },
            { "Month2", "Лютий" },
            { "Month3", "Березень" },
            { "Month4", "Квітень" },
            { "Month5", "Травень" },
            { "Month6", "Червень" },
            { "Month7", "Липень" },
            { "Month8", "Серпень" },
            { "Month9", "Вересень" },
            { "Month10", "Жовтень" },
            { "Month11", "Листопад" },
            { "Month12", "Грудень" },
            { "FiltersHeader", "Фільтри" },
            { "FilterDateFromLabel", "Дата від" },
            { "FilterDateToLabel", "Дата до" },
            { "ClearFiltersButton", "Скинути фільтри" },
            { "ReportsNav", "Звіти" },
            { "ReportsPageTitle", "Звіти" },
            { "MonthlyReportTab", "Місячний звіт" },
            { "TermReportTab", "Звіт по терміну" },
            { "YearLabel", "Рік" },
            { "MonthLabel", "Місяць" },
            { "PreviewButton", "Переглянути" },
            { "EnrolledCountCol", "Записано" },
            { "ArrivedCountCol", "Доїхали" },
            { "CompletedCountCol", "Завершили" },
            { "NoShowCountCol", "Не доїхали" },
            { "DroppedCountCol", "Викреслені" },
            { "AmountDueCol", "Нараховано" },
            { "CashSumCol", "Готівка" },
            { "TransferSumCol", "Переказ" },
            { "CompanySumCol", "Фірма платить" },
            { "ServicesSumCol", "Додаткові послуги" },
            { "NoReportDataYet", "Немає даних — натисніть «Переглянути»" },
            { "ExportError", "Помилка експорту" },
            { "TotalSumLabel", "Разом:" },
        }},
        { "pl", new Dictionary<string, string> {
            { "Students", "Studenci" },
            { "Courses", "Kursy" },
            { "Registrations", "Rejestracje" },
            { "AuditLogs", "Logi Audytu" },
            { "Total", "Razem" },
            { "Language", "Język" },
            { "Search", "Szukaj" },
            { "AddStudent", "Dodaj studenta" },
            { "SearchByName", "Wyszukaj po imieniu, numerze PKK lub obywatelstwie..." },
            { "SearchByNameOrCourse", "Wyszukaj według imienia lub kursu..." },
            { "Name", "Imię" },
            { "Citizenship", "Obywatelstwo" },
            { "PkkNumber", "Numer PKK" },
            { "Actions", "Akcje" },
            { "Edit", "Edytuj" },
            { "StudentAdded", "Student został dodany" },
            { "DataUpdated", "Dane zostały zaktualizowane" },
            { "Confirmation", "Potwierdzenie" },
            { "Delete", "Usuń" },
            { "DeleteQuestion", "Czy na pewno chcesz usunąć rejestrację studenta" },
            { "Yes", "Tak" },
            { "Cancel", "Anuluj" },
            { "Deleted", "Usunięto" },
            { "AddCourse", "Dodaj kurs" },
            { "CourseType", "Rodzaj kursu" },
            { "Student", "Student" },
            { "Course", "Kurs" },
            { "Price", "Cena" },
            { "Status", "Status" },
            { "ArrivalDate", "Data przyjazdu" },
            { "CoursePrice", "Cena kursu" },
            { "InvoiceOrHotel", "Faktura / Hotel" },
            { "NewRegistration", "Nowa rejestracja" },
            { "NoRegistrationsFound", "Nie znaleziono rejestracji" },
            { "ErrorLoadingRegistrations", "Błąd ładowania rejestracji" },
            { "EditRegistration", "Edycja rejestracji" },
            { "RegistrationCreated", "Rejestracja została utworzona" },
            { "RegistrationUpdated", "Rejestracja została zaktualizowana" },
            { "SaveError", "Błąd zapisywania" },
            { "DeleteError", "Błąd usuwania" },
            { "PaymentMethod", "Sposób płatności" },
            { "MedicalExam", "Badania lekarskie" },
            { "PsychologicalExam", "Badania psychologiczne" },
            { "Translation", "Tłumaczenie" },
            { "PowerOfAttorney", "Pełnomocnictwo" },
            { "StayRange", "Hotel: od – do (daty)" },
            { "CompanyName", "Nazwa firmy" },
            { "Notes", "Notatki" },
            { "LeaveEmptyIfOwn", "Własne — pozostaw puste" },
            { "SearchByTypeOrLanguage", "Szukaj po typie lub języku..." },
            { "Language_col", "Język" },
            { "NoCoursesFound", "Nie znaleziono kursów" },
            { "ErrorLoadingCourses", "Błąd ładowania kursów" },
            { "NewCourse", "Nowy kurs" },
            { "EditCourse", "Edycja kursu" },
            { "DeleteCourseQuestion", "Usuń kurs" },
            { "CourseAdded", "Kurs dodany" },
            { "CourseUpdated", "Kurs zaktualizowany" },
            { "CourseDeleted", "Kurs usunięty" },
            { "SelectCourseType", "Wybierz typ kursu" },
            { "SelectLanguage", "Wybierz język" },
            { "Add", "Dodaj" },
            { "Save", "Zapisz" },

            // ── Kandydaci (Candidates) 🧑‍─────────────────────────
            { "CandidatesPageTitle", "Kandydaci (Oczekujący)" },
            { "CandidatesTotalInQueue", "Wszystkich w kolejce" },
            { "SearchByNameOrPhone", "Szukaj po imieniu, nazwisku lub telefonie..." },
            { "CandidateCol", "Kandydat" },
            { "PhoneCol", "Telefon" },
            { "StatusCancelled", "Anulowany" },
            { "StatusRegistered", "Zarejestrowany" },
            { "StatusFinished", "Skończone" },
            { "StatusDropped", "Skreślony" },
            { "StatusWaiting", "Oczekujący" },
            { "ActionCol", "Akcja" },
            { "TooltipAddCourse", "Dodaj kolejny kurs" },
            { "TooltipRegister", "Zarejestruj (Przypisz do kursu)" },
            { "TooltipFinishCourse", "Zakończ kurs (Skończone)" },
            { "TooltipDropStudent", "Skreśl z listy studentów" },
            { "TooltipRemoveCourse", "Usuń z kursu (Pomyłka)" },
            { "TooltipCancelRegistration", "Anuluj rejestrację" },
            { "TooltipDeletePermanently", "Usuń trwale całą rejestrację" },
            { "CandidateDetails", "Szczegóły kandydata" },
            { "FullNameLabel", "Imię i nazwisko" },
            { "PhoneNumberLabel", "Numer telefonu" },
            { "ContactMethodLabel", "Sposób kontaktu" },
            { "PreferredCourseLabel", "Preferowany kurs" },
            { "PreferredDateLabel", "Preferowana data" },
            { "AssignToCoursesTitle", "Przypisz do kursów" },
            { "CandidateAssignedSuccess", "Kandydat zarejestrowany na wybrane kursy!" },
            { "AssignError", "Błąd podczas przypisywania" },
            { "SystemError", "Wystąpił błąd systemu. Spróbuj ponownie." },
            { "FinishCourseTitle", "Zakończ kurs" },
            { "DropFromListTitle", "Skreśl z listy" },
            { "RemoveCourseTitle", "Usuń z kursu (Pomyłka)" },
            { "CancelRegistrationTitle", "Anuluj rejestrację" },
            { "StatusUpdated", "Status został zaktualizowany." },
            { "UpdateError", "Błąd podczas aktualizacji" },
            { "EnrollmentRemoved", "Przypisanie do kursu zostało usunięte." },
            { "RemoveFromCourseError", "Błąd podczas usuwania z kursu." },
            { "CourseStatusUpdated", "Status kursu został zaktualizowany." },
            { "DeleteCandidateConfirmMessage", "Czy na pewno chcesz trwale usunąć kandydata" },
            { "YesDelete", "Tak, usuń" },
            { "CandidateDeleted", "Kandydat został trwale usunięty." },
            { "DeleteErrorGeneric", "Błąd podczas usuwania." },
            { "ErrorLoadingData", "Błąd ładowania danych" },

            // ── Registrations 📝 ──────────────────────────────────────
            { "RegistrationsPageTitle", "Rejestracje kandydatów" },
            { "AddRegistration", "Dodaj rejestrację" },
            { "ContactCol", "Kontakt" },
            { "PreferredTermCol", "Preferowany termin" },
            { "CompanyCol", "Firma" },
            { "PrivatelyText", "prywatnie" },
            { "HotelCol", "Hotel" },
            { "HotelYes", "Tak" },
            { "HotelNo", "Nie" },
            { "HotelUnknown", "Nie wiadomo" },
            { "SavedSuccessfully", "Zapisano pomyślnie" },
            { "SaveErrorDuplicate", "Błąd zapisywania (możliwy duplikat)" },

            // ── Audit Logs 🔍 ─────────────────────────────────────────
            { "Refresh", "Odśwież" },
            { "UserCol", "Użytkownik" },
            { "EntityCol", "Encja" },
            { "ActionColLog", "Akcja" },
            { "GoToCol", "Przejdź" },

            // ── Admini ─────────────────────────────────────────────
            { "AdminManagementTitle", "Zarządzanie kontami adminów" },
            { "TotalAdmins", "Razem" },
            { "AddAdmin", "Dodaj admina" },
            { "LoginCol", "Login" },
            { "RoleCol", "Rola" },
            { "CreatedAtCol", "Utworzono" },
            { "DeleteAccountTooltip", "Usuń konto" },
            { "NoAccountsFound", "Brak kont" },
            { "LoadAdminsError", "Błąd ładowania listy adminów" },
            { "AdminCreatedSuccess", "Konto admina utworzone." },
            { "CreateAdminError", "Błąd tworzenia konta." },
            { "DeleteAdminConfirmMessage", "Usunąć konto admina" },
            { "AdminDeletedSuccess", "Konto usunięte." },
            { "DeleteAdminError", "Błąd usuwania konta." },
            { "PasswordLabel", "Hasło" },
            { "PasswordHelperText", "Minimum 8 znaków" },
            { "CreateButton", "Utwórz" },

            // ── Dialogs 📋 ────────────────────────────────────────────
            { "ChooseCoursesFor", "Wybierz kursy dla kandydata" },
            { "SelectAllText", "Wybierz wszystkie" },
            { "MarkCoursesLabel", "Oznacz kursy (można kilka)" },
            { "RequiredCourseError", "Musisz wybrać przynajmniej jeden kurs" },
            { "AssignToCourses", "Przypisz do kursów" },
            { "CancelReasonPrompt", "Podaj powód anulowania rejestracji dla kandydata" },
            { "CancelReasonLabel", "Powód anulowania" },
            { "CancelReasonRequired", "Musisz podać powód anulowania!" },
            { "CancelReasonPlaceholder", "Niestety, kandydat zrezygnował..." },
            { "GoBack", "Wróć" },
            { "ConfirmCancellation", "Potwierdź anulowanie" },
            { "CandidateLabel", "Kandydat" },
            { "ActionLabel", "Akcja" },
            { "SelectCourseLabel", "Wybierz kurs" },
            { "SelectCourseRequired", "Musisz wybrać kurs" },
            { "NoActiveCoursesWarning", "Brak aktywnych kursów do wyboru." },
            { "ReasonRequiredError", "Musisz podać powód!" },
            { "RemoveCourseWarning", "Ta akcja trwale usunie przypisanie kandydata do wybranego kursu. Używaj tylko w przypadku pomyłki!" },
            { "Confirm", "Potwierdź" },
            { "ActionCancelling", "Anulowanie rejestracji" },
            { "ActionDropping", "Skreślenie z listy studentów" },
            { "ActionFinishing", "Zakończenie kursu" },
            { "ActionRemoving", "Usunięcie przypisania (pomyłka)" },
            { "ActionGeneric", "Zmiana statusu" },
            { "NotesOptional", "Uwagi (opcjonalnie)" },
            { "ReasonRequiredLabel", "Powód (wymagane)" },
            { "PlaceholderFinished", "Np. Certyfikat wydany..." },
            { "PlaceholderReason", "Podaj powód..." },

            // ── StudentDialog 👤 ──────────────────────────────────────
            { "DateOfBirth", "Data urodzenia" },
            { "RequiredField", "Pole wymagane" },
            { "OptionalPlaceholder", "Opcjonalnie" },

            // ── Login ──────────────────────────────────────────────
            { "LoginToContinue", "Zaloguj się, aby kontynuować" },
            { "LoginLabel", "Login" },
            { "LoginButton", "Zaloguj się" },
            { "FillLoginPassword", "Wpisz login i hasło." },
            { "LoginError", "Błąd logowania." },
            { "LoggedInAs", "Zalogowano jako" },
            { "LogoutButtonText", "Wyloguj się" },

            // ── SmartPriceField ────────────────────────────────────
            { "ChoosePricePlaceholder", "Wybierz lub wpisz kwotę" },

            // ── Students page ──────────────────────────────────────
            { "StudentsPageTitle", "Studenci (Obsługa po przyjeździe)" },
            { "StudentsTotalCaption", "Wszystkich studentów" },
            { "NewStudentsAutoNote", "nowi studenci pojawiają się automatycznie po przypisaniu kandydata do kursu na stronie Kandydaci" },
            { "SearchStudents", "Szukaj po imieniu, nazwisku, PKK, obywatelstwie lub kursie..." },
            { "FullNameCol", "Imię i nazwisko" },
            { "CoursesCol", "Kursy" },
            { "NoActiveCourses", "Brak aktywnych kursów" },
            { "OverallStatusCol", "Status ogólny" },
            { "AttendanceCol", "Obecność" },
            { "PaymentsCol", "Płatności" },
            { "EditBasicDataTooltip", "Edytuj dane podstawowe" },
            { "DeleteStudentTooltip", "Usuń studenta" },
            { "NoCourseAssignedInfo", "Ten student nie ma jeszcze przypisanego żadnego kursu. Przypisanie odbywa się na stronie Kandydaci." },
            { "AttendanceDocumentsTab", "Obecność i dokumenty" },
            { "AttendanceHeader", "Obecność" },
            { "AttendanceStatusLabel", "Status obecności" },
            { "ArrivalWaiting", "Oczekuje na przyjazd" },
            { "ArrivalArrived", "Dojechał" },
            { "ArrivalNoShow", "Nie dojechał" },
            { "ArrivalLate", "Spóźniony" },
            { "ArrivalDateLabel", "Data przyjazdu" },
            { "DocumentsHeader", "Dokumenty" },
            { "DocumentsStatusLabel", "Status dokumentów" },
            { "DocNotChecked", "Nie sprawdzono" },
            { "DocMissing", "Brak" },
            { "DocPartial", "Częściowo" },
            { "DocReceived", "Otrzymano" },
            { "DocNotRequired", "Niewymagane" },
            { "PassportLabel", "Paszport" },
            { "DrivingLicenseLabel", "Prawo jazdy" },
            { "PkkPkzLabel", "PKK / PKZ" },
            { "MedicalExamShortLabel", "Badania" },
            { "PaymentsTab", "Płatności" },
            { "PaymentStatusLabel", "Status płatności" },
            { "PayUnpaid", "Nie zapłacono" },
            { "PayPartial", "Częściowo zapłacono" },
            { "PayPaid", "Zapłacono" },
            { "PayOverpaid", "Nadpłata" },
            { "PayNotRequired", "Niewymagane" },
            { "SuggestedLabel", "Sugerowany" },
            { "PayCash", "Gotówka" },
            { "PayBankTransfer", "Przelew" },
            { "PayCompany", "Firma płaci" },
            { "PayMixed", "Mieszane" },
            { "PayOther", "Inne" },
            { "InvoiceLabel", "Faktura" },
            { "CoursePriceLabel", "Cena kursu (PLN)" },
            { "AmountPaidLabel", "Kwota zapłacona (PLN)" },
            { "RemainingLabel", "Pozostało" },
            { "OverpaidLabel", "Nadpłata" },
            { "FullyPaidLabel", "Zapłacono całość" },
            { "TotalDueWithServicesLabel", "Do zapłaty razem z usługami" },
            { "PaymentNotesLabel", "Uwagi do płatności" },
            { "ServicesHotelTab", "Usługi i hotel" },
            { "AdditionalServicesHeader", "Usługi dodatkowe" },
            { "MedicalExamCheckboxLabel", "Badania lekarskie" },
            { "PsychExamCheckboxLabel", "Badania psychologiczne" },
            { "TranslationCheckboxLabel", "Tłumaczenie" },
            { "PowerOfAttorneyCheckboxLabel", "Pełnomocnictwo" },
            { "PkkPkzFeeLabel", "PKK / PKZ (opłata)" },
            { "HotelHeader", "Hotel" },
            { "NeedsHotelLabel", "Potrzebny hotel" },
            { "HotelStatusLabel", "Status hotelu" },
            { "HotelNotRequired", "Niewymagany" },
            { "HotelNeeded", "Potrzebny" },
            { "HotelReserved", "Zarezerwowany" },
            { "HotelCheckedIn", "Zakwaterowany" },
            { "HotelCancelled", "Anulowany" },
            { "HotelFromLabel", "Od" },
            { "HotelToLabel", "Do" },
            { "HotelStayRangeLabel", "Zakres pobytu (tekst, opcjonalnie)" },
            { "FinalStatusTab", "Status końcowy" },
            { "CourseStatusLabel", "Status kursu" },
            { "CourseInProgress", "W trakcie" },
            { "OfficeNotesLabel", "Uwagi biura" },
            { "OfficeNotesPlaceholder", "Tylko sytuacje niestandardowe..." },
            { "SaveDataButton", "Zapisz dane" },
            { "NoStudentsInDb", "Brak studentów w bazie" },
            { "EnrollmentSaved", "Dane kursu studenta zostały zapisane." },
            { "EnrollmentSaveError", "Błąd podczas zapisywania danych." },
            { "EditDataTitle", "Edytuj dane" },
            { "DeleteStudentConfirmMessage", "Usunąć studenta" },

            // ── RegistrationDialog 📝 ──────────────────────────────────
            { "CandidateDataHeader", "Dane kandydata" },
            { "CountryCodeLabel", "Kod kraju" },
            { "PhoneNumberFieldLabel", "Numer telefonu" },
            { "PhoneFormatHelper", "Format: 500 111 222 (spacje zostaną usunięte technicznie)" },
            { "ContactLanguageLabel", "Język kontaktu" },
            { "RegistrationSourceLabel", "Źródło zgłoszenia" },
            { "SourcePhone", "Telefon" },
            { "SourceWhatsApp", "WhatsApp" },
            { "SourceCompany", "Firma" },
            { "ContactHeader", "Kontakt" },
            { "PrimaryContactLabel", "Główny sposób kontaktu" },
            { "ContactPhoneCall", "Telefon" },
            { "ContactViber", "Viber" },
            { "ContactTelegram", "Telegram" },
            { "ContactMessenger", "Messenger" },
            { "ContactSms", "SMS" },
            { "ContactNotesLabel", "Uwagi do kontaktu" },
            { "ContactNotesPlaceholder", "Np. Nie dzwonić po 18:00" },
            { "CourseAndDateHeader", "Kurs i termin (Preferowany przez klienta)" },
            { "CourseTypeLabel", "Typ kursu" },
            { "CourseInfoOnly", "Info (Tylko notatka)" },
            { "PreferredCourseDateLabel", "Preferowany termin kursu" },
            { "PlannedArrivalDateLabel", "Planowana data przyjazdu" },
            { "DateNotesLabel", "Uwagi do terminu" },
            { "CompanyHeader", "Firma" },
            { "PrivatePersonOption", "Osoba prywatna" },
            { "CompanyOption", "Firma" },
            { "UnknownOption", "Nie wiadomo" },
            { "CompanyNameFieldLabel", "Firma (Nazwa)" },
            { "HotelDialogHeader", "Hotel" },
            { "HotelFromDialogLabel", "Hotel od" },
            { "HotelToDialogLabel", "Hotel do" },
            { "HotelNotesLabel", "Uwagi do hotelu" },
            { "StatusAndNotesHeader", "Status i uwagi" },
            { "RegistrationStatusLabel", "Status rejestracji" },
            { "RegStatusNew", "Nowe zgłoszenie" },
            { "RegStatusContacted", "Skontaktowano się" },
            { "RegStatusWaitingConfirmation", "Oczekuje potwierdzenia" },
            { "RegStatusConfirmed", "Potwierdzono" },
            { "RegStatusAssigned", "Przypisano do kursu" },
            { "RegistrationNotesLabel", "Uwagi do rejestracji" },
            { "UpdateButton", "Aktualizuj" },
            { "CandidatesNav", "Kandydaci" },
            { "AdminsNav", "Admini" },
            { "CourseDatesHeader", "Terminy kursu" },
            { "AddDateButton", "Dodaj termin" },
            { "StartDateLabel", "Data od" },
            { "EndDateLabelShort", "Data do" },
            { "NoDatesYet", "Brak zaplanowanych terminów" },
            { "EnrolledStudentsHeader", "Zapisani studenci" },
            { "NoStudentsForDate", "Nikt nie jest zapisany na ten termin" },
            { "DeleteDateTooltip", "Usuń termin" },
            { "SelectDateForCourse", "Wybierz termin (opcjonalnie)" },
            { "NoDateSelected", "Bez konkretnego terminu" },
            { "DeleteDateConfirmMessage", "Usunąć termin" },
            { "FutureTermsCountCol", "Liczba przyszłych terminów" },
            { "NearestTermCol", "Najbliższy termin" },
            { "OpenAction", "Otwórz" },
            { "TemplatesHeader", "Szablony tworzenia terminów" },
            { "AddTemplateButton", "Dodaj szablon" },
            { "NoTemplatesYet", "Brak jeszcze żadnego szablonu" },
            { "GenerateButton", "Generuj" },
            { "SourceCol", "Źródło terminu" },
            { "SourceGenerated", "Wygenerowany" },
            { "SourceManual", "Ręczny" },
            { "ManuallyModifiedTooltip", "Zmieniony ręcznie po wygenerowaniu" },
            { "TermStatusLabel", "Status terminu" },
            { "TermStatusPlanned", "Zaplanowany" },
            { "TermStatusActive", "Aktywny" },
            { "TermStatusFinished", "Zakończony" },
            { "TermStatusCancelled", "Anulowany" },
            { "TermStatusMoved", "Przeniesiony" },
            { "TrainerLabel", "Trener" },
            { "DefaultPriceLabel", "Cena domyślna" },
            { "SeatLimitLabel", "Limit miejsc" },
            { "TermNotesLabel", "Uwagi do terminu" },
            { "TemplateModeLabel", "Tryb tworzenia terminów" },
            { "TemplateModeCyclic", "Cykliczny" },
            { "TemplateModeManual", "Ręczny" },
            { "DayOfWeekLabel", "Dzień tygodnia" },
            { "DayMonday", "Poniedziałek" },
            { "DayTuesday", "Wtorek" },
            { "DayWednesday", "Środa" },
            { "DayThursday", "Czwartek" },
            { "DayFriday", "Piątek" },
            { "DaySaturday", "Sobota" },
            { "DaySunday", "Niedziela" },
            { "FrequencyLabel", "Częstotliwość" },
            { "FrequencyWeekly", "Co tydzień" },
            { "FrequencyBiweekly", "Co 2 tygodnie" },
            { "FrequencyEvery3Weeks", "Co 3 tygodnie" },
            { "FrequencyMonthly", "Co miesiąc" },
            { "GenerateFromLabel", "Generuj od" },
            { "GenerateToLabel", "Generuj do" },
            { "DefaultDurationLabel", "Domyślna długość kursu (dni)" },
            { "TemplateActiveLabel", "Aktywny" },
            { "GeneratedCountMessage", "Utworzono terminów" },
            { "SkippedCountMessage", "Pominięto (już istnieją)" },
            { "GenerateError", "Błąd podczas generowania" },
            { "DeleteTemplateConfirmMessage", "Usunąć ten szablon?" },
            { "NoAvailableTermsForCourse", "Brak dostępnych terminów dla tego kursu" },
            { "OpenStudentCardAction", "Otwórz kartę studenta" },
            { "CourseVariantPreview", "Wariant kursu" },
            { "CourseTypeHelper", "Wybierz z listy lub wpisz nową wartość" },
            { "LanguageHelper", "Wybierz z listy lub wpisz nową wartość" },
            { "Month1", "Styczeń" },
            { "Month2", "Luty" },
            { "Month3", "Marzec" },
            { "Month4", "Kwiecień" },
            { "Month5", "Maj" },
            { "Month6", "Czerwiec" },
            { "Month7", "Lipiec" },
            { "Month8", "Sierpień" },
            { "Month9", "Wrzesień" },
            { "Month10", "Październik" },
            { "Month11", "Listopad" },
            { "Month12", "Grudzień" },
            { "FiltersHeader", "Filtry" },
            { "FilterDateFromLabel", "Data od" },
            { "FilterDateToLabel", "Data do" },
            { "ClearFiltersButton", "Wyczyść filtry" },
            { "ReportsNav", "Raporty" },
            { "ReportsPageTitle", "Raporty" },
            { "MonthlyReportTab", "Raport miesięczny" },
            { "TermReportTab", "Raport terminu" },
            { "YearLabel", "Rok" },
            { "MonthLabel", "Miesiąc" },
            { "PreviewButton", "Podgląd" },
            { "EnrolledCountCol", "Zapisani" },
            { "ArrivedCountCol", "Dojechali" },
            { "CompletedCountCol", "Ukończyli" },
            { "NoShowCountCol", "Nie dojechali" },
            { "DroppedCountCol", "Skreśleni" },
            { "AmountDueCol", "Kwota naliczona" },
            { "CashSumCol", "Gotówka" },
            { "TransferSumCol", "Przelew" },
            { "CompanySumCol", "Firma płaci" },
            { "ServicesSumCol", "Usługi dodatkowe" },
            { "NoReportDataYet", "Brak danych — kliknij «Podgląd»" },
            { "ExportError", "Błąd eksportu" },
            { "TotalSumLabel", "Razem:" },
        }},
        { "en", new Dictionary<string, string> {
            { "Students", "Students" },
            { "Courses", "Courses" },
            { "Registrations", "Registrations" },
            { "AuditLogs", "Audit Logs" },
            { "Total", "Total" },
            { "Language", "Language" },
            { "Search", "Search" },
            { "AddStudent", "Add Student" },
            { "SearchByName", "Search by name, PKK number or citizenship..." },
            { "SearchByNameOrCourse", "Search by name or course..." },
            { "Name", "Name" },
            { "Citizenship", "Citizenship" },
            { "PkkNumber", "PKK Number" },
            { "Actions", "Actions" },
            { "Edit", "Edit" },
            { "StudentAdded", "Student added" },
            { "DataUpdated", "Data updated" },
            { "Confirmation", "Confirmation" },
            { "Delete", "Delete" },
            { "DeleteQuestion", "Are you sure you want to delete the enrollment for" },
            { "Yes", "Yes" },
            { "Cancel", "Cancel" },
            { "Deleted", "Deleted" },
            { "AddCourse", "Add Course" },
            { "CourseType", "Course Type" },
            { "Student", "Student" },
            { "Course", "Course" },
            { "Price", "Price" },
            { "Status", "Status" },
            { "ArrivalDate", "Arrival Date" },
            { "CoursePrice", "Course Price" },
            { "InvoiceOrHotel", "Invoice / Hotel" },
            { "NewRegistration", "New Registration" },
            { "NoRegistrationsFound", "No registrations found" },
            { "ErrorLoadingRegistrations", "Error loading registrations" },
            { "EditRegistration", "Edit Registration" },
            { "RegistrationCreated", "Registration created" },
            { "RegistrationUpdated", "Registration updated" },
            { "SaveError", "Save error" },
            { "DeleteError", "Delete error" },
            { "PaymentMethod", "Payment Method" },
            { "MedicalExam", "Medical Exam" },
            { "PsychologicalExam", "Psychological Exam" },
            { "Translation", "Translation" },
            { "PowerOfAttorney", "Power of Attorney" },
            { "StayRange", "Hotel stay: from – to (dates)" },
            { "CompanyName", "Company Name" },
            { "Notes", "Notes" },
            { "LeaveEmptyIfOwn", "Own — leave blank" },
            { "SearchByTypeOrLanguage", "Search by type or language..." },
            { "Language_col", "Language" },
            { "NoCoursesFound", "No courses found" },
            { "ErrorLoadingCourses", "Error loading courses" },
            { "NewCourse", "New course" },
            { "EditCourse", "Edit course" },
            { "DeleteCourseQuestion", "Delete course" },
            { "CourseAdded", "Course added" },
            { "CourseUpdated", "Course updated" },
            { "CourseDeleted", "Course deleted" },
            { "SelectCourseType", "Select course type" },
            { "SelectLanguage", "Select language" },
            { "Add", "Add" },
            { "Save", "Save" },

            // ── Candidates 🧑‍───────────────────────────────────────
            { "CandidatesPageTitle", "Candidates (Waiting)" },
            { "CandidatesTotalInQueue", "Total in queue" },
            { "SearchByNameOrPhone", "Search by name, surname or phone..." },
            { "CandidateCol", "Candidate" },
            { "PhoneCol", "Phone" },
            { "StatusCancelled", "Cancelled" },
            { "StatusRegistered", "Registered" },
            { "StatusFinished", "Finished" },
            { "StatusDropped", "Dropped" },
            { "StatusWaiting", "Waiting" },
            { "ActionCol", "Action" },
            { "TooltipAddCourse", "Add another course" },
            { "TooltipRegister", "Register (assign to course)" },
            { "TooltipFinishCourse", "Finish course" },
            { "TooltipDropStudent", "Drop from student list" },
            { "TooltipRemoveCourse", "Remove from course (mistake)" },
            { "TooltipCancelRegistration", "Cancel registration" },
            { "TooltipDeletePermanently", "Permanently delete registration" },
            { "CandidateDetails", "Candidate details" },
            { "FullNameLabel", "Full name" },
            { "PhoneNumberLabel", "Phone number" },
            { "ContactMethodLabel", "Contact method" },
            { "PreferredCourseLabel", "Preferred course" },
            { "PreferredDateLabel", "Preferred date" },
            { "AssignToCoursesTitle", "Assign to courses" },
            { "CandidateAssignedSuccess", "Candidate registered for the selected courses!" },
            { "AssignError", "Error while assigning" },
            { "SystemError", "A system error occurred. Please try again." },
            { "FinishCourseTitle", "Finish course" },
            { "DropFromListTitle", "Drop from list" },
            { "RemoveCourseTitle", "Remove from course (mistake)" },
            { "CancelRegistrationTitle", "Cancel registration" },
            { "StatusUpdated", "Status updated." },
            { "UpdateError", "Error while updating" },
            { "EnrollmentRemoved", "Course assignment removed." },
            { "RemoveFromCourseError", "Error while removing from course." },
            { "CourseStatusUpdated", "Course status updated." },
            { "DeleteCandidateConfirmMessage", "Are you sure you want to permanently delete candidate" },
            { "YesDelete", "Yes, delete" },
            { "CandidateDeleted", "Candidate permanently deleted." },
            { "DeleteErrorGeneric", "Error while deleting." },
            { "ErrorLoadingData", "Error loading data" },

            // ── Registrations 📝 ───────────────────────────────────────
            { "RegistrationsPageTitle", "Candidate registrations" },
            { "AddRegistration", "Add registration" },
            { "ContactCol", "Contact" },
            { "PreferredTermCol", "Preferred date" },
            { "CompanyCol", "Company" },
            { "PrivatelyText", "private" },
            { "HotelCol", "Hotel" },
            { "HotelYes", "Yes" },
            { "HotelNo", "No" },
            { "HotelUnknown", "Unknown" },
            { "SavedSuccessfully", "Saved successfully" },
            { "SaveErrorDuplicate", "Save error (possible duplicate)" },

            // ── Audit Logs 🔍 ──────────────────────────────────────────
            { "Refresh", "Refresh" },
            { "UserCol", "User" },
            { "EntityCol", "Entity" },
            { "ActionColLog", "Action" },
            { "GoToCol", "Go to" },

            // ── Admin Users ─────────────────────────────────────────
            { "AdminManagementTitle", "Admin account management" },
            { "TotalAdmins", "Total" },
            { "AddAdmin", "Add admin" },
            { "LoginCol", "Login" },
            { "RoleCol", "Role" },
            { "CreatedAtCol", "Created" },
            { "DeleteAccountTooltip", "Delete account" },
            { "NoAccountsFound", "No accounts found" },
            { "LoadAdminsError", "Error loading admin list" },
            { "AdminCreatedSuccess", "Admin account created." },
            { "CreateAdminError", "Error creating account." },
            { "DeleteAdminConfirmMessage", "Delete admin account" },
            { "AdminDeletedSuccess", "Account deleted." },
            { "DeleteAdminError", "Error deleting account." },
            { "PasswordLabel", "Password" },
            { "PasswordHelperText", "Minimum 8 characters" },
            { "CreateButton", "Create" },

            // ── Dialogs 📋 ─────────────────────────────────────────────
            { "ChooseCoursesFor", "Choose courses for candidate" },
            { "SelectAllText", "Select all" },
            { "MarkCoursesLabel", "Mark courses (multiple allowed)" },
            { "RequiredCourseError", "You must select at least one course" },
            { "AssignToCourses", "Assign to courses" },
            { "CancelReasonPrompt", "Provide the reason for cancelling registration for candidate" },
            { "CancelReasonLabel", "Cancellation reason" },
            { "CancelReasonRequired", "You must provide a cancellation reason!" },
            { "CancelReasonPlaceholder", "Unfortunately, the candidate withdrew..." },
            { "GoBack", "Back" },
            { "ConfirmCancellation", "Confirm cancellation" },
            { "CandidateLabel", "Candidate" },
            { "ActionLabel", "Action" },
            { "SelectCourseLabel", "Select course" },
            { "SelectCourseRequired", "You must select a course" },
            { "NoActiveCoursesWarning", "No active courses to choose from." },
            { "ReasonRequiredError", "You must provide a reason!" },
            { "RemoveCourseWarning", "This action will permanently remove the candidate's assignment to the selected course. Use only in case of a mistake!" },
            { "Confirm", "Confirm" },
            { "ActionCancelling", "Cancelling registration" },
            { "ActionDropping", "Dropping from student list" },
            { "ActionFinishing", "Finishing course" },
            { "ActionRemoving", "Removing assignment (mistake)" },
            { "ActionGeneric", "Status change" },
            { "NotesOptional", "Notes (optional)" },
            { "ReasonRequiredLabel", "Reason (required)" },
            { "PlaceholderFinished", "E.g. Certificate issued..." },
            { "PlaceholderReason", "Provide a reason..." },

            // ── StudentDialog 👤 ───────────────────────────────────────
            { "DateOfBirth", "Date of birth" },
            { "RequiredField", "Required field" },
            { "OptionalPlaceholder", "Optional" },

            // ── Login ───────────────────────────────────────────────
            { "LoginToContinue", "Log in to continue" },
            { "LoginLabel", "Login" },
            { "LoginButton", "Log in" },
            { "FillLoginPassword", "Enter login and password." },
            { "LoginError", "Login error." },
            { "LoggedInAs", "Logged in as" },
            { "LogoutButtonText", "Log out" },

            // ── SmartPriceField ─────────────────────────────────────
            { "ChoosePricePlaceholder", "Choose or enter an amount" },

            // ── Students page ──────────────────────────────────────
            { "StudentsPageTitle", "Students (Post-arrival service)" },
            { "StudentsTotalCaption", "Total students" },
            { "NewStudentsAutoNote", "new students appear automatically once a candidate is assigned to a course on the Candidates page" },
            { "SearchStudents", "Search by name, surname, PKK, citizenship or course..." },
            { "FullNameCol", "Full name" },
            { "CoursesCol", "Courses" },
            { "NoActiveCourses", "No active courses" },
            { "OverallStatusCol", "Overall status" },
            { "AttendanceCol", "Attendance" },
            { "PaymentsCol", "Payments" },
            { "EditBasicDataTooltip", "Edit basic data" },
            { "DeleteStudentTooltip", "Delete student" },
            { "NoCourseAssignedInfo", "This student doesn't have a course assigned yet. Assignment happens on the Candidates page." },
            { "AttendanceDocumentsTab", "Attendance and documents" },
            { "AttendanceHeader", "Attendance" },
            { "AttendanceStatusLabel", "Attendance status" },
            { "ArrivalWaiting", "Waiting for arrival" },
            { "ArrivalArrived", "Arrived" },
            { "ArrivalNoShow", "No-show" },
            { "ArrivalLate", "Late" },
            { "ArrivalDateLabel", "Arrival date" },
            { "DocumentsHeader", "Documents" },
            { "DocumentsStatusLabel", "Document status" },
            { "DocNotChecked", "Not checked" },
            { "DocMissing", "Missing" },
            { "DocPartial", "Partial" },
            { "DocReceived", "Received" },
            { "DocNotRequired", "Not required" },
            { "PassportLabel", "Passport" },
            { "DrivingLicenseLabel", "Driving license" },
            { "PkkPkzLabel", "PKK / PKZ" },
            { "MedicalExamShortLabel", "Medical exam" },
            { "PaymentsTab", "Payments" },
            { "PaymentStatusLabel", "Payment status" },
            { "PayUnpaid", "Unpaid" },
            { "PayPartial", "Partially paid" },
            { "PayPaid", "Paid" },
            { "PayOverpaid", "Overpaid" },
            { "PayNotRequired", "Not required" },
            { "SuggestedLabel", "Suggested" },
            { "PayCash", "Cash" },
            { "PayBankTransfer", "Bank transfer" },
            { "PayCompany", "Company pays" },
            { "PayMixed", "Mixed" },
            { "PayOther", "Other" },
            { "InvoiceLabel", "Invoice" },
            { "CoursePriceLabel", "Course price (PLN)" },
            { "AmountPaidLabel", "Amount paid (PLN)" },
            { "RemainingLabel", "Remaining" },
            { "OverpaidLabel", "Overpaid" },
            { "FullyPaidLabel", "Fully paid" },
            { "TotalDueWithServicesLabel", "Total due including services" },
            { "PaymentNotesLabel", "Payment notes" },
            { "ServicesHotelTab", "Services and hotel" },
            { "AdditionalServicesHeader", "Additional services" },
            { "MedicalExamCheckboxLabel", "Medical exam" },
            { "PsychExamCheckboxLabel", "Psychological exam" },
            { "TranslationCheckboxLabel", "Translation" },
            { "PowerOfAttorneyCheckboxLabel", "Power of attorney" },
            { "PkkPkzFeeLabel", "PKK / PKZ (fee)" },
            { "HotelHeader", "Hotel" },
            { "NeedsHotelLabel", "Needs hotel" },
            { "HotelStatusLabel", "Hotel status" },
            { "HotelNotRequired", "Not required" },
            { "HotelNeeded", "Needed" },
            { "HotelReserved", "Reserved" },
            { "HotelCheckedIn", "Checked in" },
            { "HotelCancelled", "Cancelled" },
            { "HotelFromLabel", "From" },
            { "HotelToLabel", "To" },
            { "HotelStayRangeLabel", "Stay range (text, optional)" },
            { "FinalStatusTab", "Final status" },
            { "CourseStatusLabel", "Course status" },
            { "CourseInProgress", "In progress" },
            { "OfficeNotesLabel", "Office notes" },
            { "OfficeNotesPlaceholder", "Non-standard situations only..." },
            { "SaveDataButton", "Save data" },
            { "NoStudentsInDb", "No students in database" },
            { "EnrollmentSaved", "Student course data saved." },
            { "EnrollmentSaveError", "Error while saving data." },
            { "EditDataTitle", "Edit data" },
            { "DeleteStudentConfirmMessage", "Delete student" },

            // ── RegistrationDialog 📝 ──────────────────────────────────
            { "CandidateDataHeader", "Candidate data" },
            { "CountryCodeLabel", "Country code" },
            { "PhoneNumberFieldLabel", "Phone number" },
            { "PhoneFormatHelper", "Format: 500 111 222 (spaces will be removed automatically)" },
            { "ContactLanguageLabel", "Contact language" },
            { "RegistrationSourceLabel", "Registration source" },
            { "SourcePhone", "Phone" },
            { "SourceWhatsApp", "WhatsApp" },
            { "SourceCompany", "Company" },
            { "ContactHeader", "Contact" },
            { "PrimaryContactLabel", "Primary contact method" },
            { "ContactPhoneCall", "Phone call" },
            { "ContactViber", "Viber" },
            { "ContactTelegram", "Telegram" },
            { "ContactMessenger", "Messenger" },
            { "ContactSms", "SMS" },
            { "ContactNotesLabel", "Contact notes" },
            { "ContactNotesPlaceholder", "E.g. Don't call after 6 PM" },
            { "CourseAndDateHeader", "Course and date (client's preference)" },
            { "CourseTypeLabel", "Course type" },
            { "CourseInfoOnly", "Info (note only)" },
            { "PreferredCourseDateLabel", "Preferred course date" },
            { "PlannedArrivalDateLabel", "Planned arrival date" },
            { "DateNotesLabel", "Date notes" },
            { "CompanyHeader", "Company" },
            { "PrivatePersonOption", "Private person" },
            { "CompanyOption", "Company" },
            { "UnknownOption", "Unknown" },
            { "CompanyNameFieldLabel", "Company (name)" },
            { "HotelDialogHeader", "Hotel" },
            { "HotelFromDialogLabel", "Hotel from" },
            { "HotelToDialogLabel", "Hotel to" },
            { "HotelNotesLabel", "Hotel notes" },
            { "StatusAndNotesHeader", "Status and notes" },
            { "RegistrationStatusLabel", "Registration status" },
            { "RegStatusNew", "New submission" },
            { "RegStatusContacted", "Contacted" },
            { "RegStatusWaitingConfirmation", "Waiting for confirmation" },
            { "RegStatusConfirmed", "Confirmed" },
            { "RegStatusAssigned", "Assigned to course" },
            { "RegistrationNotesLabel", "Registration notes" },
            { "UpdateButton", "Update" },
            { "CandidatesNav", "Candidates" },
            { "AdminsNav", "Admins" },
            { "CourseDatesHeader", "Course dates" },
            { "AddDateButton", "Add date" },
            { "StartDateLabel", "Start date" },
            { "EndDateLabelShort", "End date" },
            { "NoDatesYet", "No dates scheduled yet" },
            { "EnrolledStudentsHeader", "Enrolled students" },
            { "NoStudentsForDate", "No one is enrolled for this date" },
            { "DeleteDateTooltip", "Delete date" },
            { "SelectDateForCourse", "Select date (optional)" },
            { "NoDateSelected", "No specific date" },
            { "DeleteDateConfirmMessage", "Delete date" },
            { "FutureTermsCountCol", "Future terms" },
            { "NearestTermCol", "Nearest term" },
            { "OpenAction", "Open" },
            { "TemplatesHeader", "Term generation templates" },
            { "AddTemplateButton", "Add template" },
            { "NoTemplatesYet", "No templates yet" },
            { "GenerateButton", "Generate" },
            { "SourceCol", "Source" },
            { "SourceGenerated", "Generated" },
            { "SourceManual", "Manual" },
            { "ManuallyModifiedTooltip", "Manually edited after generation" },
            { "TermStatusLabel", "Term status" },
            { "TermStatusPlanned", "Planned" },
            { "TermStatusActive", "Active" },
            { "TermStatusFinished", "Finished" },
            { "TermStatusCancelled", "Cancelled" },
            { "TermStatusMoved", "Moved" },
            { "TrainerLabel", "Trainer" },
            { "DefaultPriceLabel", "Default price" },
            { "SeatLimitLabel", "Seat limit" },
            { "TermNotesLabel", "Term notes" },
            { "TemplateModeLabel", "Term creation mode" },
            { "TemplateModeCyclic", "Cyclic" },
            { "TemplateModeManual", "Manual" },
            { "DayOfWeekLabel", "Day of week" },
            { "DayMonday", "Monday" },
            { "DayTuesday", "Tuesday" },
            { "DayWednesday", "Wednesday" },
            { "DayThursday", "Thursday" },
            { "DayFriday", "Friday" },
            { "DaySaturday", "Saturday" },
            { "DaySunday", "Sunday" },
            { "FrequencyLabel", "Frequency" },
            { "FrequencyWeekly", "Weekly" },
            { "FrequencyBiweekly", "Every 2 weeks" },
            { "FrequencyEvery3Weeks", "Every 3 weeks" },
            { "FrequencyMonthly", "Monthly" },
            { "GenerateFromLabel", "Generate from" },
            { "GenerateToLabel", "Generate to" },
            { "DefaultDurationLabel", "Default course length (days)" },
            { "TemplateActiveLabel", "Active" },
            { "GeneratedCountMessage", "Terms created" },
            { "SkippedCountMessage", "Skipped (already exist)" },
            { "GenerateError", "Error while generating" },
            { "DeleteTemplateConfirmMessage", "Delete this template?" },
            { "NoAvailableTermsForCourse", "No available terms for this course" },
            { "OpenStudentCardAction", "Open student card" },
            { "CourseVariantPreview", "Course variant" },
            { "CourseTypeHelper", "Choose from the list or type a new value" },
            { "LanguageHelper", "Choose from the list or type a new value" },
            { "Month1", "January" },
            { "Month2", "February" },
            { "Month3", "March" },
            { "Month4", "April" },
            { "Month5", "May" },
            { "Month6", "June" },
            { "Month7", "July" },
            { "Month8", "August" },
            { "Month9", "September" },
            { "Month10", "October" },
            { "Month11", "November" },
            { "Month12", "December" },
            { "FiltersHeader", "Filters" },
            { "FilterDateFromLabel", "Date from" },
            { "FilterDateToLabel", "Date to" },
            { "ClearFiltersButton", "Clear filters" },
            { "ReportsNav", "Reports" },
            { "ReportsPageTitle", "Reports" },
            { "MonthlyReportTab", "Monthly report" },
            { "TermReportTab", "Term report" },
            { "YearLabel", "Year" },
            { "MonthLabel", "Month" },
            { "PreviewButton", "Preview" },
            { "EnrolledCountCol", "Enrolled" },
            { "ArrivedCountCol", "Arrived" },
            { "CompletedCountCol", "Completed" },
            { "NoShowCountCol", "No-show" },
            { "DroppedCountCol", "Dropped" },
            { "AmountDueCol", "Amount due" },
            { "CashSumCol", "Cash" },
            { "TransferSumCol", "Bank transfer" },
            { "CompanySumCol", "Company pays" },
            { "ServicesSumCol", "Additional services" },
            { "NoReportDataYet", "No data yet — click 'Preview'" },
            { "ExportError", "Export error" },
            { "TotalSumLabel", "Total:" },
        }}
    };
 
    public string GetString(string key)
    {
        if (_translations.TryGetValue(_currentLanguage, out var langDict) &&
            langDict.TryGetValue(key, out var value))
            return value;
        return key;
    }
}
