// <auto-generated />
using System;
using CourseManagementApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CourseManagementApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CourseManagementApi.Data.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_salt");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("app_users");
                });

            modelBuilder.Entity("CourseManagementApi.Data.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("changed_by");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.ToTable("audit_logs");
                });

            modelBuilder.Entity("CourseManagementApi.Data.Entities.CandidateRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_user_id");

                    b.Property<string>("CompanyName")
                        .HasColumnType("text")
                        .HasColumnName("company_name");

                    b.Property<string>("ContactNotes")
                        .HasColumnType("text")
                        .HasColumnName("contact_notes");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country_code");

                    b.Property<string>("CourseLanguage")
                        .HasColumnType("text")
                        .HasColumnName("course_language");

                    b.Property<string>("CourseType")
                        .HasColumnType("text")
                        .HasColumnName("course_type");

                    b.Property<string>("CourseVariantCode")
                        .HasColumnType("text")
                        .HasColumnName("course_variant_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DateNotes")
                        .HasColumnType("text")
                        .HasColumnName("date_notes");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<DateTime?>("HotelFrom")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("hotel_from");

                    b.Property<string>("HotelNotes")
                        .HasColumnType("text")
                        .HasColumnName("hotel_notes");

                    b.Property<DateTime?>("HotelTo")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("hotel_to");

                    b.Property<string>("InitialInformation")
                        .HasColumnType("text")
                        .HasColumnName("initial_information");

                    b.Property<string>("NationalNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("national_number");

                    b.Property<string>("NeedsHotel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("needs_hotel");

                    b.Property<string>("PayerType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payer_type");

                    b.Property<string>("PhoneE164")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_e164");

                    b.Property<DateTime?>("PlannedArrivalDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("planned_arrival_date");

                    b.Property<string>("PreferredContactLanguage")
                        .HasColumnType("text")
                        .HasColumnName("preferred_contact_language");

                    b.Property<DateTime?>("PreferredCourseDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("preferred_course_date");

                    b.Property<string>("PrimaryContactMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("primary_contact_method");

                    b.Property<string>("RegistrationNotes")
                        .HasColumnType("text")
                        .HasColumnName("registration_notes");

                    b.Property<string>("RegistrationSource")
                        .HasColumnType("text")
                        .HasColumnName("registration_source");

                    b.Property<string>("SecondaryContactMethods")
                        .HasColumnType("text")
                        .HasColumnName("secondary_contact_methods");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("PhoneE164");

                    b.ToTable("candidate_registrations");
                });

            modelBuilder.Entity("CourseManagementApi.Data.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CourseType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("course_type");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.HasKey("Id");

                    b.ToTable("courses");
                });

            modelBuilder.Entity("CourseManagementApi.Data.Entities.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("numeric")
                        .HasColumnName("amount_paid");

                    b.Property<DateTime?>("ArrivalDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("arrival_date");

                    b.Property<string>("AttendanceStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("attendance_status");

                    b.Property<string>("CompanyName")
                        .HasColumnType("text")
                        .HasColumnName("company_name");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<decimal>("CoursePrice")
                        .HasColumnType("numeric")
                        .HasColumnName("course_price");

                    b.Property<bool>("DocDrivingLicense")
                        .HasColumnType("boolean")
                        .HasColumnName("doc_driving_license");

                    b.Property<bool>("DocMedical")
                        .HasColumnType("boolean")
                        .HasColumnName("doc_medical");

                    b.Property<bool>("DocPassport")
                        .HasColumnType("boolean")
                        .HasColumnName("doc_passport");

                    b.Property<bool>("DocPkk")
                        .HasColumnType("boolean")
                        .HasColumnName("doc_pkk");

                    b.Property<string>("DocumentsStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("documents_status");

                    b.Property<bool>("HasInvoice")
                        .HasColumnType("boolean")
                        .HasColumnName("has_invoice");

                    b.Property<DateTime?>("HotelFrom")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("hotel_from");

                    b.Property<string>("HotelStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hotel_status");

                    b.Property<string>("HotelStayRange")
                        .HasColumnType("text")
                        .HasColumnName("hotel_stay_range");

                    b.Property<DateTime?>("HotelTo")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("hotel_to");

                    b.Property<decimal?>("MedicalExamPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("medical_exam_price");

                    b.Property<bool>("NeedsHotel")
                        .HasColumnType("boolean")
                        .HasColumnName("needs_hotel");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("text")
                        .HasColumnName("payment_method");

                    b.Property<string>("PaymentNotes")
                        .HasColumnType("text")
                        .HasColumnName("payment_notes");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payment_status");

                    b.Property<decimal?>("PkzPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("pkz_price");

                    b.Property<decimal?>("PowerOfAttorneyPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("power_of_attorney_price");

                    b.Property<decimal?>("PsychologicalExamPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("psychological_exam_price");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<bool>("SvcMedical")
                        .HasColumnType("boolean")
                        .HasColumnName("svc_medical");

                    b.Property<bool>("SvcPowerOfAttorney")
                        .HasColumnType("boolean")
                        .HasColumnName("svc_power_of_attorney");

                    b.Property<bool>("SvcPsychological")
                        .HasColumnType("boolean")
                        .HasColumnName("svc_psychological");

                    b.Property<bool>("SvcTranslation")
                        .HasColumnType("boolean")
                        .HasColumnName("svc_translation");

                    b.Property<decimal?>("TranslationPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("translation_price");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId", "CourseId")
                        .IsUnique();

                    b.ToTable("enrollments");
                });

            modelBuilder.Entity("CourseManagementApi.Data.Entities.FinancialTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("EnrollmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("enrollment_id");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("text")
                        .HasColumnName("invoice_number");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("transaction_date");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("transaction_type");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId");

                    b.ToTable("financial_transactions");
                });

            modelBuilder.Entity("CourseManagementApi.Data.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Citizenship")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("citizenship");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("PkkNumber")
                        .HasColumnType("text")
                        .HasColumnName("pkk_number");

                    b.HasKey("Id");

                    b.ToTable("students");
                });

            modelBuilder.Entity("CourseManagementApi.Data.Entities.Enrollment", b =>
                {
                    b.HasOne("CourseManagementApi.Data.Entities.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseManagementApi.Data.Entities.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CourseManagementApi.Data.Entities.FinancialTransaction", b =>
                {
                    b.HasOne("CourseManagementApi.Data.Entities.Enrollment", "Enrollment")
                        .WithMany()
                        .HasForeignKey("EnrollmentId");

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("CourseManagementApi.Data.Entities.Course", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("CourseManagementApi.Data.Entities.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
